analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'
urlpatterns = [
    path('ps_analysis/', views.graphView, name='ps_analysis'),
    path('monthly_balance_sheet/', views.BalanceSheetListView.as_view(),
         name='monthly_balance_sheet')
]

sale/urls.py
from django.urls import path
from . import views

app_name = 'sale'
urlpatterns = [
    path('sales/', views.SalesCreateView.as_view(), name='sales'),
    path('salesdetail/<int:pk>',
         views.SalesDetailView.as_view(), name="sales_detail"),
    path('salesmade/', views.SalesListView.as_view(), name='sales_made'),
    path('sale-daybook/',views.DayBookListView.as_view(),name='daybook')
]

analysis/models.py
from django.db import models

# Create your models here.

entry/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.urls import reverse
# Create your models here.


class Purchase(models.Model):
    invoice = models.SmallIntegerField(primary_key=True, blank=False)
    ch_no = models.SmallIntegerField(blank=True, null=True)
    vendor = models.CharField(max_length=128, blank=False)
    date = models.DateField(default=timezone.now, blank=False)

    def __str__(self):
        return self.vendor

    def get_absolute_url(self):
        return reverse('entry:purchase_detail', kwargs={'pk': self.pk})


class PurchaseDetail(models.Model):

    PRODUCT_CHOICES = (
        ('WOOD', 'Wood'),
        ('G LASS', 'Glass'),
        ('PLASTIC', 'Plastic'),
        ('LEATHER', 'Leather'),
        ('FABRIC', 'Fabric'),
        ('STEEL', 'Steel'),
    )
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=30,
                                    choices=PRODUCT_CHOICES,
                                    default='WOOD')
    quantity = models.PositiveSmallIntegerField(blank=False)
    rate = models.IntegerField(blank=False)
    total = models.IntegerField(blank=False)
    remarks = models.CharField(max_length=250)
    created_at = models.DateField(default=timezone.now, blank=False)

    def __str__(self):
        return (self.product_name)

sale/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Sale(models.Model):
    invoice = models.SmallIntegerField(primary_key=True, blank=False)
    ch_no = models.SmallIntegerField(blank=True, null=True)
    purchasers = models.CharField(max_length=128, blank=False)
    date = models.DateField(default=timezone.now, blank=False)

    def __str__(self):
        return (self.purchasers)

    def get_absolute_url(self):
        return reverse('sale:sales_detail', kwargs={'pk': self.pk})


class SaleDetail(models.Model):
    PRODUCT_CHOICES = (
        ('WOOD', 'Wood'),
        ('GLASS', 'Glass'),
        ('PLASTIC', 'Plastic'),
        ('LEATHER', 'Leather'),
        ('FABRIC', 'Fabric'),
        ('STEEL', 'Steel'),
    )
    sales = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=30, choices=PRODUCT_CHOICES,
                                    default='WOOD')
    quantity = models.PositiveSmallIntegerField(blank=False)
    rate = models.IntegerField(blank=False)
    total = models.IntegerField(blank=False)
    remarks = models.CharField(max_length=250, blank=True, null=True)
    created_at = models.DateField(default=timezone.now, blank=False)

    def __str__(self):
        return (self.product_name)

analysis/views.py
from django.shortcuts import render
from django.views import generic
import json
from django.http import JsonResponse, HttpResponse
from django.db.models import Sum
from entry.models import Purchase, PurchaseDetail
from datetime import date
from sale.models import Sale, SaleDetail
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def graphView(request):
    purchase_qs = PurchaseDetail.objects.all()
    sale_qs = SaleDetail.objects.all()
    categories = list()
    purchase_no = list()
    sale_no = list()
    sum = SaleDetail.objects.filter(
        product_name='STEEL', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='STEEL', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('STEEL')

    sum = SaleDetail.objects.filter(
        product_name='WOOD', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='WOOD', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('WOOD')

    sum = SaleDetail.objects.filter(
        product_name='PLASTIC', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='PLASTIC', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('PLASTIC')

    sum = SaleDetail.objects.filter(
        product_name='FABRIC', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='FABRIC', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('FABRIC')

    sum = SaleDetail.objects.filter(
        product_name='LEATHER', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='LEATHER', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('LEATHER')

    sum = SaleDetail.objects.filter(
        product_name='GLASS', created_at__year='2018').aggregate(Sum('quantity'))
    sale_no.append(sum.get('quantity__sum'))
    sum = PurchaseDetail.objects.filter(
        product_name='GLASS', created_at__year='2018').aggregate(Sum('quantity'))
    purchase_no.append(sum.get('quantity__sum'))
    categories.append('GLASS')

    return render(request, 'analysis/ps_analysis.html', {
        'categories': json.dumps(categories),
        'purchase_no': json.dumps(purchase_no),
        'sale_no': json.dumps(sale_no)
    })


class BalanceSheetListView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'

    model = Purchase
    template_name = 'analysis/balance-sheet.html'

    def get_context_data(self, *args, **kwargs):
        today = date.today()
        context = {}
        context['purchases'] = Purchase.objects.filter(
            date__year=today.year, date__month=today.month)
        context['sales'] = Sale.objects.filter(
            date__year=today.year, date__month=today.month)
        psum = PurchaseDetail.objects.filter(
            created_at__year=today.year, created_at__month=today.month).aggregate(Sum('total'))
        ssum = SaleDetail.objects.filter(
            created_at__year=today.year, created_at__month=today.month).aggregate(Sum('total'))
        context['net'] = (int(psum.get('total__sum') or 0)-int(ssum.get('total__sum') or 0))
        return context

analysis/templates/analysis/balance-sheet.html
{% extends "base.html" %}{% block head_title %}Profit-Loss | {{ block.super }}{% endblock %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            Purchase
        </div>
        <div class="col-6">
            Sales
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ol>
                {% for purchase in purchases %}
                <li> Vendor: {{ purchase.vendor}}</li> Date: {{ purchase.date}}
                <br> Invoice: {{ purchase.invoice }} | Ch No: {{purchase.ch_no}}
                <ul>
                    {% for purchaseitems in purchase.purchasedetail_set.all %}

                    <div>
                        <li> Product Name: {{ purchaseitems.product_name }}</li>
                        Quantity: {{purchaseitems.quantity}}
                        <br> Rate: {{purchaseitems.rate}}
                        <br> Total: {{purchaseitems.total}}
                    </div>
                    {% endfor %}
                </ul> {% empty %}
                <li> NO Purchase this month.</li>
                {% endfor %}
            </ol>
        </div>
        <div class="col-6">
            <ol>
                {% for sale in sales %}
                <li> Purchaser: {{ sale.purchasers}}</li> Date: {{ sale.date}}
                <br> Invoice: {{ sale.invoice }} | Ch No: {{sale.ch_no}}
                <ul>
                    {% for saleitems in sale.saledetail_set.all %}

                    <div>
                        <li> Product Name: {{ saleitems.product_name }}</li>
                        Quantity: {{saleitems.quantity}}
                        <br> Rate: {{saleitems.rate}}
                        <br> Total: {{saleitems.total}}
                    </div>
                    {% endfor %}
                </ul> {% empty %}
                <li>No Sales this month.</li>
                {% endfor %}
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            Net Profit:
        </div>

        <div class="col-6">
            Rs. {{net}}
        </div>
    </div>

</div>
{% endblock content %}

analysis/templates/analysis/ps_analysis.html
{% extends "base.html" %} {% block head_title %}Graphical Analysis | {{ block.super }}{% endblock %} {% block content %}
<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Purchase/Sale of Product this Month'
        },
        xAxis: {
            categories: {{ categories| safe }}
        },
        series: [{
            name: 'Purchase',
            data: {{ purchase_no }},
            color: 'blue'
        }
            , {
            name: 'Sale',
            data: {{ sale_no }},
            color: 'red'
        }
        ]
    });
</script> {% endblock content %}