analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'
urlpatterns = [
    path('ps_analysis/', views.graphView, name='ps_analysis'),
    path('monthly_balance_sheet/', views.BalanceSheetListView.as_view(),
         name='monthly_balance_sheet')
]

entry/urls.py
from django.urls import path
from . import views

app_name = 'entry'
urlpatterns = [
    path('purchase/', views.PurchaseCreateView.as_view(), name='purchase'),
    path('purchasedetail/<int:pk>',
         views.PurchaseDetailView.as_view(), name="purchase_detail"),
    path('purchasemade/', views.PurchaseListView.as_view(), name='purchase_made'),
    path('purchase-daybook/',views.DayBookListView.as_view(),name='daybook')
    

]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('viewinventory/', views.viewInventoryView.as_view(), name='viewinventory'),
    path('notification/', views.notificationView.as_view(), name='notification'),
]

sale/urls.py
from django.urls import path
from . import views

app_name = 'sale'
urlpatterns = [
    path('sales/', views.SalesCreateView.as_view(), name='sales'),
    path('salesdetail/<int:pk>',
         views.SalesDetailView.as_view(), name="sales_detail"),
    path('salesmade/', views.SalesListView.as_view(), name='sales_made'),
    path('sale-daybook/',views.DayBookListView.as_view(),name='daybook')
]

templates/snippets/nav.html
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

<nav class="navbar navbar-light bg-info">
        <div class="container-fluid">
                <a class="navbar-brand" href="#">
                        <img src="{% static "images/my-ledger.PNG" %}" width="30" height="30" class="d-inline-block align-top"
                                alt=""> My Ledger
                </a>
                <ul class="nav nav-pills ">

                        <li class="nav-item">
                                <a class="nav-link text-dark" href="{% url 'home' %}">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Purchase
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'entry:purchase' %}">Entry</a>
                                        <a class="dropdown-item" href="{% url 'entry:purchase_made' %}">View Purchase</a>
                                        <a class="dropdown-item" href="{% url 'entry:daybook' %}">Day Book</a>
                                </div>
                        </li>
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Sales
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'sale:sales' %}">Entry</a>
                                        <a class="dropdown-item" href="{% url 'sale:sales_made' %}">View Sales</a>
                                        <a class="dropdown-item" href="{% url 'sale:daybook' %}">Day Book</a>
                                </div>
                        </li>
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Analysis
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'analysis:ps_analysis' %}">Purchase-Sales Graph</a>
                                        <a class="dropdown-item" href="{% url 'analysis:monthly_balance_sheet' %}">Monthly Balance-Sheet</a>
                                </div>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" href="{% url 'inventory:viewinventory' %}">View Inventory</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" href="{% url 'inventory:notification' %}">Notifications</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" href="#Help">Help</a>
                        </li>

                        <li class="nav-item">
                                <a class="nav-link text-dark" href="/logout/">Log Out(
                                        <strong>{{request.user.username}}</strong>)</a>
                        </li>

                </ul>
        </div>
</nav>